Current = "0.1.1"

[[Files]]
  Path = "README.md"
  Prefix = "v"
  Postfix = ""
  IsNumber = false

[[Files]]
  Path = "README.md"
  Prefix = "n"
  Postfix = ""
  IsNumber = true

[[Files]]
  Path = "release_tag"
  Prefix = "v"
  Postfix = ""
  IsNumber = false
