Current = "0.0.5"

[[Files]]
  Path = "README.md"
  Prefix = "v"
  Postfix = ""
  IsSequential = false

[[Files]]
  Path = "README.md"
  Prefix = ""
  Postfix = "th release"
  IsSequential = true

[[Files]]
  Path = "release_tag"
  Prefix = "v"
  Postfix = ""
  IsSequential = false
